### ISSUE TITLE
Symfony 3.x

### ISSUE THREAD

**Issue by tomaszpolska** [fsi-open/teryt-database-bundle#22]
It doesn't run with Symfony 3.2, when do you plan to upgrade?

**Comment by szymach** [comment]
Hey, it would be helpful if you could provide info on what does not work exactly. Will make it faster to adjust the bundle :)

**Comment by tomaszpolska** [comment]
The installation doesn't work. Your bundle requires Symfony 2.7 or 3.0. I'm using Composer and it says "Your requirements could not be resolved to an installable set of packages".

**Comment by szymach** [comment]
It says [3.0 or higher](https://github.com/fsi-open/teryt-database-bundle/blob/master/composer.json#L15), so it probably means some other package is causing issues for you. Can you provide the output from `composer update`?

**Comment by tomaszpolska** [comment]
Sorry, you're right. Here is the output:

    Problem 1

    - fsi/teryt-database-bundle v1.0.0 requires symfony/symfony ^2.3.39 -> satisfiable by symfony/symfony[2.3.x-dev, 2.4.x-dev, 2.5.x-dev, 2.6.x-dev, 2.7.x-dev, 2.8.x-dev, v2.3.39, v2.3.40, v2.3.41, v2.3.42, v2.4.0, v2.4.0-BETA1, v2.4.0-BETA2, v2.4.0-RC1, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.0-BETA1, v2.5.0-BETA2, v2.5.0-RC1, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.0-BETA1, v2.6.0-BETA2, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.0-BETA1, v2.7.0-BETA2, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9] but these conflict with your requirements or minimum-stability.

    - fsi/teryt-database-bundle 1.0.x-dev requires symfony/symfony ^2.3.39 -> satisfiable by symfony/symfony[2.3.x-dev, 2.4.x-dev, 2.5.x-dev, 2.6.x-dev, 2.7.x-dev, 2.8.x-dev, v2.3.39, v2.3.40, v2.3.41, v2.3.42, v2.4.0, v2.4.0-BETA1, v2.4.0-BETA2, v2.4.0-RC1, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.0-BETA1, v2.5.0-BETA2, v2.5.0-RC1, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.0-BETA1, v2.6.0-BETA2, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.0-BETA1, v2.7.0-BETA2, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9] but these conflict with your requirements or minimum-stability.

    - Installation request for fsi/teryt-database-bundle 1.0.*@dev -> satisfiable by fsi/teryt-database-bundle[1.0.x-dev, v1.0.0].

**Comment by szymach** [comment]
Well you are using the `1.*` branch, which does not support newer Symfony versions, please change it to `2.0@dev` and it should work fine.

**Comment by tomaszpolska** [comment]
Thanks, in the end  it should be like this `"fsi/teryt-database-bundle": "2.0.*@dev"`

Correct installation steps in README.md please.

**Comment by szymach** [comment]
Thanks for the submission, we will have the README updated shortly.
